### ISSUE TITLE
Self-Closing Meta TAGS, CSS, SCRIPT

### ISSUE THREAD

**Issue by bachilli** [scotch-io/stencil#4]
can you close the meta tags and css to validate in w3c html?

<link rel="stylesheet" bla bla bla />
<meta name bla bla bla bla bla />

**Comment by whatnickcodes** [comment]
When you say close the meta tags and CSS, I believe you're talking about the trailing slash. Am I correct?

Somewhere in the docs, it mentions that Stencil requires the HTML5 Doctype (mainly because of the HTML5 Helper/dependency). If you switch your doctype declaration to:

``` html
<!doctype html>
```

Your HTML will validate as those are all "void elements" and no longer required in html5 to close. [Source 1](http://www.w3.org/html/wg/drafts/html/master/syntax.html) and [Source 2](http://stackoverflow.com/questions/7366344/do-we-still-need-end-slashes-in-html5).

If that isn't an option for you for whatever reason, you can go into the HTML5 Helper ([application/helpers/HTML5_helper](https://github.com/scotch-io/stencil/blob/master/application/helpers/stencil_helper.php)) and modify two functions. The CSS change will be on line 16 and the meta tag change will be on line 94.

I hope this helps! I'm going to close this issue (please star this repo if you haven't!).

**Comment by bachilli** [comment]
Thanks!

## 

Philippe
(53) 8103-3040

2013/8/7 Nicholas Cerminara notifications@github.com
